version: '2'
services:
  web:
    build: valueset-workbench
    links:
     - mongodb:db
     - cts2
     - standardizer
    expose:
      - "3000"
    environment:
     NODE_ENV: docker-development
     FORCE_SSL: "yes"
    env_file: ${ENV_FILE}

  mongodb:
    image: mongo
    volumes:
     - vsw_mongo:/data/db
    ports:
     - "27017:27017"

  proxy:
    image: dockercloud/haproxy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    links:
     - web
    environment:
      DEFAULT_SSL_CERT: ${DEFAULT_SSL_CERT}
      FORCE_SSL: "yes"
    ports:
     - "443:443"
     - "80:80"

  arango:
    image: arangodb:2.8.7
    volumes:
    - vsw_arangodb:/var/lib/arangodb
    ports:
    - "8529:8529"
    environment:
    - ARANGO_NO_AUTH=1

  cts2-elasticsearch:
    image: elasticsearch:2.0.2
    volumes:
    - vsw_elasticsearch:/usr/share/elasticsearch/data
    ports:
    - "9201:9200"
    - "9301:9300"

  cts2:
    image: valuesetworkbench/arangodb-service
    ports:
    - "9999:8080"
    - "62911:62911"
    links:
    - arango
    - cts2-elasticsearch
    environment:
    - SERVER_ROOT=http://$SERVER_HOST:9999

  standardizer:
    image: valuesetworkbench/valueset-standardizer
    links:
    - cts2-elasticsearch
    expose:
    - "8080"
    environment:
    - "elasticSearchHost=cts2-elasticsearch"

volumes:
  vsw_elasticsearch:
  vsw_mongo:
  vsw_arangodb:
